[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pihole-ai"
version = "0.1.0"
description = "AI-assisted Pi-hole monitoring and threat analysis"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }

authors = [
    { name = "Hampus Rikard Karlsson" }
]

dependencies = [
    "flask>=3.1.0",
    "ollama>=0.6.2",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "actions*",
    "collector*",
    "core*",
    "engine*",
    "ui*",
]
